services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
    networks:
      - ls

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - LOCALSTACK_HOSTNAME=localstack
    depends_on:
      - localstack
    networks:
      - ls
networks:
    ls:
        driver: bridge