version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - localstack
    environment:
      - AWS_ENDPOINT=http://localstack:4566